### PR TITLE
Add mkdocs-material docs gen and include CI docs (review)

### LINKED ISSUE #21: Proposal for docs in repo
### Summary

Keep documentation within the repo instead of a remote wiki or Github wiki. 

### Rationale

From a developer experience perspective, it is easier to clone and have everything you need to reference locally rather than having to externally reference something.

This minimises context switching and aids the practice of keeping documentation updated as it is closer to the codebase. 

### Solution Proposal

Leverage automatic documentation generation via https://squidfunk.github.io/mkdocs-material.

This integrates well with Github, providing automatic docs for your repo at `<username>.github.io/<repository>`. 

**Sample structure:**

```
docs
├── ci
│   ├── gitleaks.md
│   ├── golang-ci.md
│   └── semantic-release.md
└── starter.md # docs on how to get started with this repo
```

**Example:**

https://cli.urfave.org/

Generated from `./docs` directory:
https://github.com/urfave/cli/tree/main/docs

### PR DESCRIPTION
**Pull request by haani-niyaz**
Hi @shukra-in-spirit @vancanhuit , I've raised this PR for review on:

1. Documentation structure
2. Quickstart content
3. CI pages structure
4. CI content for gitleaks, pre-commit, mkdocs-material and golangci-lint

The documentation on publish will look similar to:
https://haani-niyaz.github.io/golang-template-repository/

Closes #21 and #28.

Required actions:

- [x] Proof read content 
- [x] Enable gh-pages in template repo settings as mentioned in #21 
- [x] Add Sonarqube CI docs
- [x] Reconcile with #23 

@AlvinKuruvilla, there was an urgency to finish this piece of work so I've stepped in. Happy to discuss with you if required.

### CODE REVIEW

**Comment by jeffy-mathew** [comment]
since this is related to docs. 
shall we use https://opencollective.com/vale to do a copy check?
https://github.com/errata-ai/vale-action - seems helpful in GitHub actions context

**Comment by haani-niyaz** [comment]
> since this is related to docs. shall we use https://opencollective.com/vale to do a copy check? https://github.com/errata-ai/vale-action - seems helpful in GitHub actions context

This definitely looks interesting. We should have a story to explore it :)

For the purpose of this MR though, a more technical documentation review is required to validate if the information is helpful for repo owners to get started.

**Review by shukra-in-spirit — APPROVED** [review]

**Comment by haani-niyaz** [comment]
@shukra-in-spirit  thanks for merging this. Just checking if gh-pages was setup in the repo as per:
https://github.com/rog-golang-buddies/golang-template-repository/issues/21#issuecomment-1171874696

The site is URL is retuning a 404 atm.

**Comment by shukra-in-spirit** [comment]
Hey, I updated it.

**Pull request merged**
