### PR TITLE
Create draft PR template

### LINKED ISSUE #47: Add a PR template
Include a PR template so we have consistent process to describe the PR and include what we would generally expect to be done before raising the PR.

A sample template has been added below. 

As per https://github.com/rog-golang-buddies/golang-template-repository/wiki/Platform-Team-Onboarding-Guide use `github` as the commit scope.

### Example

```
## Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have checked my code/docs and corrected any misspellings
```

### PR DESCRIPTION
**Pull request by pallasite99**
* Fixes #47

### CODE REVIEW

**Comment by shukra-in-spirit** [comment]
Can you add a status section on top with:
- [ ] Waiting for review
- [ ] Waiting for comment resolution
- [ ] Waiting for merge
- [ ] Draft
- [ ] Trivial PR (nominal cosmetic/typo/whitespace changes)

**Review by shukra-in-spirit — CHANGES_REQUESTED** [review]
can you also add a small section for linking it to the issue(s) that it is resolving,

**Comment by pallasite99** [comment]
@shukra-in-spirit sure I will.

a linked issue(s) section and the status one, cool

**Comment by pallasite99** [comment]
@shukra-in-spirit made the requested changes

**Comment by shukra-in-spirit** [comment]
I had missed out the issues mentioned at the top of the page.
- I added Semantic Versioning part as well.
- And some cosmetic changes

Rest looks good to me. I am approving. Feel free to merge before the v0.2.0 release.
@haani-niyaz can you look into including this too in the release.

**Comment by shukra-in-spirit** [comment]
Keeping my fingers crossed for the same.

**Pull request merged**
