### PR TITLE
draft go-test pr

### PR DESCRIPTION
**Pull request by shukra-in-spirit**
Issue: https://github.com/rog-golang-buddies/golang-template-repository/issues/35
A workflow is required to run go test on events .g: on: [pull_request, push, workflow_dispatch]

Steps:
Added a starter go-test github action file from https://gfgfddgleb.medium.com/how-to-test-your-go-code-with-github-actions-f15881d46089

This is the job
```
build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Test
      run: go test -v ./...
```
      
@haani-niyaz please review.
@jeffy-mathew You can work on this PR if you want. Sorry, it was a little urgent to get it started.

### CODE REVIEW

**Comment by pallasite99** [comment]
@shukra-in-spirit this is already done as part of `.github/workflows/release.yml`

It is working so I guess this won't be needed afaik

**Review by jeffy-mathew — APPROVED** [review]

**Comment by shukra-in-spirit** [comment]
Hey @pallasite99 
I did not quite follow, L33 of that file does the go setup right? And not the go-test I believe..

**Comment by jeffy-mathew** [comment]
@pallasite99 also that workflow runs only on push to main branch. I assume we need to run tests on every PR, workflow_dispatch etc

**Comment by pallasite99** [comment]
@jeffy-mathew @shukra-in-spirit I missed the test part of your changes and thought this was just doing the setup, apologies 🙃

**Pull request merged**
